### ISSUE TITLE
Make library usable with Node

### ISSUE THREAD

**Issue by raffazizzi** [mangalam-research/salve-dom#31]
I'd like to use `salve-dom` in Node, but the reliance on `window` is getting in the way. Any chance the code could be adjusted to inject an alternative `window`, e.g. via `jsdom`?

**Comment by lucaju** [comment]
Hi @raffazizzi. I have the same problem. My plan was actually to use `salve-dom` in `Web Worker` to unload the heavy validation task off of the main thread. Have you managed to make it work on `Node` using `jsdom`? If you did, can you share your solution?
@lddubeau , do you think you can take a look at this?

**Comment by raffazizzi** [comment]
Hi @lucaju. I made it possible in my fork (https://github.com/raffazizzi/salve-dom) but also added a bunch of other stuff that I needed for the [VS Code extension](https://marketplace.visualstudio.com/items?itemName=raffazizzi.sxml) I was writing and it may be a bit difficult to extract that specific part from the rest, though feel free to take a look!

**Comment by raffazizzi** [comment]
Whoops nevermind, I ended up making my changes to salve not salve-dom: https://github.com/raffazizzi/salve

**Comment by lucaju** [comment]
Oh. Great. Thank you very much @raffazizzi I will definitely take a look at this right away :)

**Comment by lddubeau** [comment]
Sorry, when this was posted in 2020, I must have run into an email problem. I never saw this notice.

Note that `salve-dom` and `salve` are no longer in active development, as the project to which they were attached has been abandoned. I do not know if or when they will be developed again.

`salve-dom` expects a DOM (Document Object Model) and AFAIK DOM specifies that `window` must exist. I recommend to use `jsdom` if you want to use `salve-dom` with a fake DOM, but other solutions might work like Cheerio, for instance. I just know `jsdom` more than other libraries.

It is possible to use Salve alone without a DOM by just using the `salve` library.

I'm going to close this as I don't see any change necessary to `salve-dom`. I can reopen if someone convinces me otherwise.
